<a href="https://colab.research.google.com/github/masum-auch/AI-Engineer/blob/main/Numpy%20%26%20Pandas/Numpy/02_basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is NumPy?

NumPy is a library in Python that makes scientific calculations fast and easy.



# Key topics:

**ndarray**: n-dimensional array, where all values ​​are of the same type.


# Functions:


*  Mathematical and logical calculations

*  Array reshaping

* Sorting, selecting

* File I/O

* Fourier transform

* Linear algebra (matrix multiply, inverse)

* Statistics (mean, std)

* Random simulation



# NumPy Arrays Vs Python Lists (Sequences)

### Size change

* NumPy arrays are fixed-size when created.

* Python lists are dynamic, meaning they can be made larger or smaller later.

* To change the size of a NumPy array, a new array is created, and the old one is deleted.

### Data type

* All elements in a NumPy array must be of the same data type.

* Therefore, all elements in memory are of the same size.

* Python lists can hold mixed types.

### Mathematical and other operations

* Mathematical operations on large datasets can be performed quickly and easily using NumPy arrays.

* Doing the same thing with Python lists takes more code and time.

## Used in many packages

* Almost all Python packages, like SciPy, Pandas, Matplotlib, etc, use NumPy arrays.

* When given a Python list, they convert it to a NumPy array and then process it.

* The output is usually a NumPy array.

In [6]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
# dtype try
np.array([7,1,3],dtype=bool)
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
# np.arange
np.arange(1,11).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
# with reshape
np.arange(16).reshape(2, 2, 2, 2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [25]:
#np.ones and np.zeros
np.ones((3,4))
np.ones((3, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
#np.random
np.random.random((3, 3))

array([[0.00541499, 0.92082229, 0.59689183],
       [0.68898049, 0.30665765, 0.00995489],
       [0.56976013, 0.6199053 , 0.39497306]])

In [30]:
np.random.random((5, 3, 2))

array([[[0.82376866, 0.23677704],
        [0.36236898, 0.6408661 ],
        [0.88818244, 0.25167383]],

       [[0.1099319 , 0.42617365],
        [0.63003858, 0.9416473 ],
        [0.15739495, 0.52175991]],

       [[0.59605406, 0.3673304 ],
        [0.93319931, 0.52860021],
        [0.16218019, 0.44141726]],

       [[0.53834246, 0.19610375],
        [0.13909832, 0.11932378],
        [0.6343241 , 0.99345723]],

       [[0.4179991 , 0.01651359],
        [0.82125047, 0.80818647],
        [0.6490794 , 0.70509316]]])

In [35]:
#np.linspacs
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [37]:
np.linspace(-5, 5, 10, dtype= int)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  5])

In [38]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])