<a href="https://colab.research.google.com/github/masum-auch/AI-Engineer/blob/main/Numpy%20%26%20Pandas/Numpy/03_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy learn Again part 2

In [2]:
import numpy as np

In [6]:
a1= np.arange(10)
a2= np.arange(12, dtype= float).reshape(3, 4)
a3= np.arange(8).reshape(2, 2, 2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#ndim
a3.ndim

3

In [10]:
#shape
a3.shape

(2, 2, 2)

In [12]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [13]:
#itemsize
a2.itemsize

8

In [14]:
# dtype
print(a1.dtype)

int64


In [15]:
print(a2.dtype, a3.dtype)

float64 int64


In [16]:
#changing dtype
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [17]:
print(a1.dtype)

int64


# Array Operations

In [19]:
a4= np.arange(12).reshape(3, 4)
a5= np.arange(12, 24).reshape(3, 4)

a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
#scaler operations
#arithmeric

a5 + 3

array([[15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

In [25]:
#relational

a5 == 15

(array([[False, False, False,  True],
        [False, False, False, False],
        [False, False, False, False]]),
 22)

In [27]:
#vactor operations
#arithmetric

a5 ** 2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

# Array Functions

In [36]:
a6 = np.random.random((3,3))
a7 = np.round(a6*100)
a7

array([[54., 31., 69.],
       [53., 14.,  7.],
       [75., 88., 46.]])

In [44]:
# min/max/sum/prod
# 0 > col or 1 > row

np.max(a7, axis= 0)

array([75., 88., 69.])

In [45]:
np.prod(a7, axis= 0)

array([214650.,  38192.,  22218.])

In [51]:
# mean/median/std/var

# np.mean(a7)
np.median(a7)
# np.std(a7)
# np.var(a7)

np.float64(53.0)

In [52]:
# trigonomoetric functions
np.sin(a6)

array([[0.51138284, 0.30819945, 0.64034666],
       [0.50789781, 0.14206583, 0.07089896],
       [0.68336282, 0.77133331, 0.44599251]])

In [53]:
# dot product
a8 = np.arange(12).reshape(3,4)
a9 = np.arange(12,24).reshape(4,3)

np.dot(a8,a9)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [54]:
# log and exponents
np.exp(a8)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [58]:
# round/floor/ceil

np.floor(np.random.random((2,3))*100)

array([[72., 30., 46.],
       [79., 12., 63.]])