<a href="https://colab.research.google.com/github/masum-auch/AI-Engineer/blob/main/Numpy%20%26%20Pandas/Numpy/04_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Again NumPy | Let's Start This topic part 3

## Indexing and Slicing

In [2]:
import numpy as np

In [3]:
a1= np.arange(10)
a2= np.arange(12).reshape(3, 4)
a3= np.arange(8).reshape(2, 2, 2)

In [4]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [5]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a2[1, 1]

np.int64(5)

In [8]:
a1[3]

np.int64(3)

In [9]:
a3[1, 1, 0]

np.int64(6)

In [10]:
a3[0, 1, 1]

np.int64(3)

In [11]:
a3[0, 0, 1]

np.int64(1)

In [12]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a2[1, 0]

np.int64(4)

In [14]:
a2[2, 1]

np.int64(9)

In [15]:
a2[2, 3]

np.int64(11)

In [18]:
#slicing
a1[-1]

np.int64(9)

In [19]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a2[:, 2]

array([ 2,  6, 10])

In [21]:
a2[2, :]

array([ 8,  9, 10, 11])

In [24]:
a2[::, 2]

array([ 2,  6, 10])

In [25]:
a1[2:5:2]

array([2, 4])

In [29]:
a1[2::3]

array([2, 5, 8])

In [30]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [31]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a2[0::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [33]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [36]:
a4 = np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [41]:
a4[::2,0, ::2]

array([[ 0,  2],
       [18, 20]])

In [42]:
a4[::2, 1, ::2]

array([[ 3,  5],
       [21, 23]])

In [45]:
a4[2,1:, 1:]

array([[22, 23],
       [25, 26]])