<a href="https://colab.research.google.com/github/masum-auch/AI-Engineer/blob/main/Numpy%20%26%20Pandas/Numpy/05_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Again NumPy | Let's Start This topic part 3

### Iterating

In [1]:
import numpy as np

In [2]:
a1= np.arange(10)
a2= np.arange(12).reshape(3, 4)
a3= np.arange(8).reshape(2, 2, 2)

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [10]:
a4= np.arange(27).reshape(3, 3, 3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
for i in a4:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [12]:
for i in np.nditer(a4):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [14]:
# for i in np.ndindex(a4):
#   print(i)

### Reshaping

In [17]:
#reshape
a5= np.arange(20).reshape(4,5)
a5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
#transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [22]:
np.transpose(a3)
a3.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [24]:
#ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
a4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [26]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking

In [29]:
#horizental stacking
a5= np.arange(16).reshape(4,4)
a6= np.arange(16, 32).reshape(4,4)
a6

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [31]:
np.hstack((a5, a6))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [32]:
np.hstack((a6, a5, a6))

array([[16, 17, 18, 19,  0,  1,  2,  3, 16, 17, 18, 19],
       [20, 21, 22, 23,  4,  5,  6,  7, 20, 21, 22, 23],
       [24, 25, 26, 27,  8,  9, 10, 11, 24, 25, 26, 27],
       [28, 29, 30, 31, 12, 13, 14, 15, 28, 29, 30, 31]])

In [33]:
np.hstack((a6, a5))

array([[16, 17, 18, 19,  0,  1,  2,  3],
       [20, 21, 22, 23,  4,  5,  6,  7],
       [24, 25, 26, 27,  8,  9, 10, 11],
       [28, 29, 30, 31, 12, 13, 14, 15]])

In [34]:
#vertical stacking
np.vstack((a5, a6))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [35]:
np.vstack((a6, a5, a5))

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Splitting

In [43]:
#horizental splitting
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
np.hsplit(a5, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [48]:
a6

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [49]:
np.hsplit(a6, 2)

[array([[16, 17],
        [20, 21],
        [24, 25],
        [28, 29]]),
 array([[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]])]

In [55]:
np.hsplit(a4,3)

[array([[[ 0,  1,  2]],
 
        [[ 9, 10, 11]],
 
        [[18, 19, 20]]]),
 array([[[ 3,  4,  5]],
 
        [[12, 13, 14]],
 
        [[21, 22, 23]]]),
 array([[[ 6,  7,  8]],
 
        [[15, 16, 17]],
 
        [[24, 25, 26]]])]

In [56]:
#vertical splitting
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.vsplit(a5, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [58]:
np.vsplit(a5, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [59]:
np.vsplit(a6, 2)

[array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31]])]

In [60]:
np.vsplit(a6, 4)

[array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]]),
 array([[24, 25, 26, 27]]),
 array([[28, 29, 30, 31]])]