<a href="https://colab.research.google.com/github/masum-auch/AI-Engineer/blob/main/Numpy%20%26%20Pandas/Numpy/06_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy array vs Python list

In [1]:
#seed
#list
a = [i for i in range(10000000)]
b= [i for i in range(10000000, 20000000)]

c= []
import time
start= time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

4.41370964050293


In [2]:
#numpy
import numpy as np

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.22548413276672363


In [3]:
4.41/0.22

20.045454545454547

In [4]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [7]:
a = np.arange(10000000,dtype=np.int32)
sys.getsizeof(a)

40000112

### Advanced Indexing



In [8]:
# Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a[1,2]

np.int64(6)

In [10]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [12]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
# Fancy Indexing

a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [13]:
#fancy indexing
a[[0, 2, 3, 5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [14]:
a[[3, 4]]

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])