<a href="https://colab.research.google.com/github/masum-auch/AI-Engineer/blob/main/Numpy%20%26%20Pandas/Numpy/08_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Broadcasting



In [1]:
import numpy as np

In [2]:
a= np.arange(6).reshape(2,3)
b= np.arange(6,12).reshape(2,3)

a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a,b

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]))

In [4]:
a+b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [5]:
a2=  np.arange(6).reshape(2,3)
b2= np.arange(3).reshape(1,3)


b2

array([[0, 1, 2]])

### Use Broadcasting

In [6]:
a2 + b2

array([[0, 2, 4],
       [3, 5, 7]])

In [7]:
a2 + 10 #yes possible(10, 10, 10)

array([[10, 11, 12],
       [13, 14, 15]])

In [8]:
X = np.array([[65, 70, 80],
              [60, 68, 75],
              [72, 74, 85]])

mean = X.mean(axis=0)
X_centered = X - mean


In [9]:
X

array([[65, 70, 80],
       [60, 68, 75],
       [72, 74, 85]])

In [10]:
X_centered

array([[-0.66666667, -0.66666667,  0.        ],
       [-5.66666667, -2.66666667, -5.        ],
       [ 6.33333333,  3.33333333,  5.        ]])

In [11]:
a3= np.arange(12).reshape(4,3)
b3= np.arange(3)

a3
b3

array([0, 1, 2])

In [12]:
#use broadcasting

a3 + b3

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [13]:
a4= np.arange(12).reshape(3,4)
b4= np.arange(3)

print(a4)
print(b4)

#why not work broadcasting

print(a4 + b4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [14]:
X = np.array([[1,2],
              [3,4],
              [5,6]])

weights = np.array([0.2, 0.4])

y_pred = X * weights

In [15]:
y_pred

array([[0.2, 0.8],
       [0.6, 1.6],
       [1. , 2.4]])

In [16]:
a5= np.arange(3).reshape(3,1)
b5= np.arange(3).reshape(1,3)


print(a5)
print(b5)

print(a5 + b5)

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


Why Broadcasting is CRITICAL for AI Engineers

🚀 Faster than loops

🧠 Cleaner math code

💾 Memory efficient

📐 Matches ML equations directly

In [17]:
a6= np.arange(3).reshape(1,3)
a7= np.arange(4).reshape(4,1)

print(a6,a7)

[[0 1 2]] [[0]
 [1]
 [2]
 [3]]


In [18]:
a6 + a7

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [20]:
a8= np.arange(16).reshape(4,4)
a9= np.arange(4).reshape(2,2)

print(a8)
print(a9)

print(a8 + a9)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 