<a href="https://colab.research.google.com/github/masum-auch/AI-Engineer/blob/main/Numpy%20%26%20Pandas/Numpy/09_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working with mathematical formulas | Numpy

In [1]:
import numpy as np

In [2]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#sin calculate
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [4]:
#cos calculate
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [5]:
# tan calculate
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [6]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
# cosec calculate
angle_rad = np.pi / 4

cosec= 2/np.sin(a)

print(cosec)

[        inf  2.37679021  2.19950034 14.17233479 -2.64269742 -2.08567043
 -7.15779909  3.04420213  2.02151244  4.85297329]


In [8]:
# sigmoid calculate
def sigmoid(array):
  return 1/1+np.exp(-((array)))


a2= np.arange(20)

sigmoid(a2)

array([2.        , 1.36787944, 1.13533528, 1.04978707, 1.01831564,
       1.00673795, 1.00247875, 1.00091188, 1.00033546, 1.00012341,
       1.0000454 , 1.0000167 , 1.00000614, 1.00000226, 1.00000083,
       1.00000031, 1.00000011, 1.00000004, 1.00000002, 1.00000001])

In [9]:
# mean squared error

actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)